### ISSUE TITLE
Cross Section Retrieval for Fitter

### ISSUE THREAD

**Issue by cthorpe123** [NuSoftHEP/Geant4Reweight#12]
The following lines from `G4Reweighter.cc` are used to obtain the cross sections to compare with data by the Fitter:

```
double G4Reweighter::GetInelasticXSec(double p) {
  SetMomentum(p);

  return ( inelastic_proc->GetCrossSectionDataStore()->GetCrossSection(
             dynamic_part, testMaterial) *cm );
}

double G4Reweighter::GetExclusiveXSec(double p, std::string cut) {
  return (exclusiveFracs[cut]->Eval(p)*GetInelasticXSec(p));
}

double G4Reweighter::GetElasticXSec(double p) {
  SetMomentum(p);

  return ( elastic_proc->GetCrossSectionDataStore()->GetCrossSection(
            dynamic_part, testMaterial) *cm );
}
```

These contain factors for the material density which need to be divided out before use by the Fitter. They also should be converted to millibarn.

**Comment by cathalsweeney** [comment]
This is fallout from when I [modified the code](https://github.com/NuSoftHEP/Geant4Reweight/commit/9c8a87cf7fc85403fc2a402dbf847d10acb8b317) to allow for complex materials i.e. mixtures, not just single element detectors. If I recall correctly,  the current way we're calling `GetCrossSection()` returns `1/(mean free path) [cm^-1]`  . We used to call it a different way , and it returned a value in millibarns. 

From looking at how `GetNominalMFP()` used to be called vs how it is called now, I think the conversion you need to do to do is

```
xsec [mb] = (1e27 * Atomic Mass * GetInelasticXSec() ) / (Material Density  * Avogadro's Number)
```

**Comment by cathalsweeney** [comment]
But I would ask that this change be made in the fitting code rather than the reweighting code if possible? It's not possible to provide an atomic mass for a complex material, which is the whole reason I changed the way we retrieve xsecs from geant4

**Comment by calcuttj** [comment]
Thanks for looking into this Cathal. I can get to this today

**Comment by calcuttj** [comment]
This has been solved for a while, sorry for not notifying 

https://github.com/NuSoftHEP/Geant4Reweight/pull/14
