### ISSUE TITLE
Configurable physics lists

### ISSUE THREAD

**Issue by cathalsweeney** [NuSoftHEP/Geant4Reweight#23]
The geant4 physics lists are hardcoded in `PredictionBase/G4CascadePhysicsList.cc`. It would be nice to be able to configure the physics list using a fcl. This would feed through to not only G4Cascade, but also G4CrossSection, G4Reweighter, and a couple of other places

**Comment by admlw** [comment]
To add some more context here - for NOvA right now we're investigating using an alternate EM physics lists (EMZ from G4EmStandardPhysics_option4) and we'll want to run G4Reweight for that - right now `G4EmStandardPhysics` is setup by default.

**Comment by calcuttj** [comment]
Sorry I haven't seen this yet. I'll try this out today and I'll ask for a release soon

**Comment by calcuttj** [comment]
By the way, if you have any more suggestions on functionality please let me know -- and if I don't respond promptly feel free to send an email :)

**Comment by calcuttj** [comment]
Started working on this [branch](https://github.com/NuSoftHEP/Geant4Reweight/tree/feature/calcuttj_configurable_physlist). Will have to flesh out some more stuff to make it configurable. Would one of you be willing to test when it's ready?

**Comment by cathalsweeney** [comment]
I'm taking a look at this in a local build of geant4reweight. If I have the necessary permissions I'll push any changes I make to the feature branch you're working on. Looks like the remaining work is mostly just adding in a new fhicl parameter in G4Cascade.cc etc.

**Comment by cathalsweeney** [comment]
The configurable physics lists seems to work for me in some local tests! I've created a pull request which just allows the configuring to be done for G4Cascade etc. : 
https://github.com/NuSoftHEP/Geant4Reweight/pull/25

Might be worth an new official build of Geant4Reweight with this new feature?

**Comment by cathalsweeney** [comment]
Hi @lgarren (please redirect me if necessary). NOvA would like a release with the new features introduced via feature/calcuttj_configurable_physlist (which are already available in the latest LArSoft release). What is the best way to go about this? 

Despite what a pull request between branches suggests, I think there are only 11 files that we actually want changes in. I am happy to try do some surgery to introduce the necessary changes into the NOvA branch, but am worried that the history will become messy.

**Comment by lgarren** [comment]
@cathalsweeney  Would you work with @calcuttj  to make a PR for the nova_v01_16_br branch?

**Comment by cathalsweeney** [comment]
Yes I will get to work on that, and I'll loop Jake in when necessary. Thanks Lynn

**Comment by cathalsweeney** [comment]
Hi @lgarren , a pull request has been merged into nova_v01_16_br, and the version number has been bumped in CMakeLists.txt

**Comment by lgarren** [comment]
The nu v3_13_04h distribution is now available on SciSoft with geant4reweight v01_16_05.
